In [ ]:
import numpy as np

a = np.array([1,5,7])
a1 = np.array([[1,5,7], [2,5,9]])
print(a)
print(a1)
print("print me 2nd index 3rd value", a1[1][2])
print(np.arange(10)) #its like range but u can use in numpyonly , better optimisation then range 
print(a.ndim)
print(a1.ndim) # dimension 2d, 3d
a.shape
print(a1.shape)
len(a1)

[1 5 7]
[[1 5 7]
 [2 5 9]]
print me 2nd index 3rd value 9
[0 1 2 3 4 5 6 7 8 9]
1
2
(2, 3)


2

In [10]:
import numpy as np
a = np.array([1,5,7])
a1 = np.array([[1,5,7,6], [2,5,9,8],[3,4,7,9]])
print(a1.ndim)
print(a1.shape)
print(len(a1))

2
(3, 4)
3


In [ ]:
#python List
L = range(1000)
#%timeit[i==2 for i in L]
%timeit a==2

1.37 µs ± 12.9 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


In [11]:
L = np.arange(1000)
%timeit L==2

1.71 µs ± 27.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [3]:
import numpy as np
a = np.array([[9,3,7],[1,3,4]])

print (a)
print(a.ndim)
print(a.shape)
print(len(a))
print(a[1][1])
a[1][1]=6
print(a)

[[9 3 7]
 [1 3 4]]
2
(2, 3)
2
3
[[9 3 7]
 [1 6 4]]


In [21]:
ls = np.array([[[1,3,2],[2,6,3]],[[5,7,6],[3,7,2]]])
print(ls)
ls[0][1][2]
print("shape is: ",ls.shape)
print(ls.ndim)

[[[1 3 2]
  [2 6 3]]

 [[5 7 6]
  [3 7 2]]]
shape is:  (2, 2, 3)
3


In [48]:
#using linespace

ls= np.linspace(1,2,4)
ls

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [24]:
#common array
a= np.ones((3,3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
a= np.zeros((3,3))
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
a = np.eye(2,3)
a

array([[1., 0., 0.],
       [0., 1., 0.]])

In [4]:
a = np.diag((1,2,3,4,5))
print(a.shape)
a

(5, 5)


array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [5]:
np.diag(a)

array([1, 2, 3, 4, 5])

In [6]:
#create array using random
#create an array of the givrn shape and populate it with random sample from uniform distribution over(0,1)
a = np.random.randn(4)
a

array([-1.73708593, -1.10753249, -1.08183812, -0.25016932])

In [7]:
a = np.arange(10)
a.dtype

dtype('int32')

In [8]:
a = np.arange(10,dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
#the default datatype is float for zeros & ones function
a = np.zeros((3,3))
print(a)
a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [11]:
d = np.array([1+2j, 2+4j])
print(d.dtype)
d

complex128


array([1.+2.j, 2.+4.j])

In [12]:
b = np.array([True,False,True,False])
print(b.dtype)

bool


In [ ]:
s = np.array(['sam','john']) #unicode character
print(s.dtype)

<U4


In [14]:
a = np.arange(10)
print(a[5])
a

5


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:9:2] #start , end(exclusive), step

array([1, 3, 5, 7])

In [ ]:
a = np.arange(10)
a[5:] = 10 #this command from index 5 will print 10 till last index of this array
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [24]:
b= np.arange(5)
a[5:] = b[::-1] #assignig so array b will assign value in reverse 4,3,2,1,0. because of [::-1]
print(b)
print(a)

[0 1 2 3 4]
[0 1 2 3 4 4 3 2 1 0]


In [25]:
# copies
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [27]:
c =a[::3]
c

array([0, 3, 6, 9])

In [28]:
print(id(a))
print(id(b))
print(id(c))

2258746408080
2258746407504
2258746406736


In [29]:
np.may_share_memory(a,b)

True

In [30]:
np.may_share_memory(a,c)

True

In [31]:
np.may_share_memory(b,c)

True

In [43]:
a[0]= 10
b

array([10,  2,  4,  6,  8])

In [44]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [46]:
a = np.arange(10)
c = a[::2].copy() #force a copy and it will use another memory
# c =a[: :2]
c

array([0, 2, 4, 6, 8])

In [41]:
np.may_share_memory(a,c)

False

In [47]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
a=np.array([[1,2,3],
          [4,5,6]])
b= np.array([10,20,30])
a+b

array([[11, 22, 33],
       [14, 25, 36]])